<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<whydahuser>
    <identity>
        <UID>leon.ho@test.com</UID>
        <timestamp>638726482</timestamp>
        <lifespan>647832</lifespan>
        <issuer>Whydah</issuer>
        <securitylevel>0</securitylevel>
        <DEFCON>DEFCON5</DEFCON>
        <username>leon</username>
        <cellPhone>123456</cellPhone>
        <email>leon.ho@test.com</email>
        <firstname>Leon</firstname>
        <lastname>Ho</lastname>
        <personref>1</personref>
        <UID>leon.ho@test.com</UID>
    </identity>
    <applications>
        <application>
            <appId>3</appId>
            <applicationName>Whydah</applicationName>
            <organizationName>Whydah.net</organizationName>
            <roleName>developer</roleName>
            <roleValue>20</roleValue>
        </application>
        <application>
            <appId>1</appId>
            <applicationName>UserAdmin</applicationName>
            <organizationName>Whydah.net</organizationName>
            <roleName>UserAdmin</roleName>
            <roleValue></roleValue>
        </application>
        <application>
            <appId>2</appId>
            <applicationName>Mobilefirst</applicationName>
            <organizationName>Whydah.net</organizationName>
            <roleName>client</roleName>
            <roleValue>10</roleValue>
        </application>
        <application>
            <appId>4</appId>
            <applicationName>ACS</applicationName>
            <organizationName>Whydah.net</organizationName>
            <roleName>Administrator</roleName>
            <roleValue>true</roleValue>
        </application>
        <application>
            <appId>3</appId>
            <applicationName>Whydah</applicationName>
            <organizationName>Whydah.net</organizationName>
            <roleName>WhydahUserAdmin</roleName>
            <roleValue>99</roleValue>
        </application>
        <application>
            <appId>4</appId>
            <applicationName>ACS</applicationName>
           <organizationName>Whydah.net</organizationName>
           <roleName>Manager</roleName>
            <roleValue></roleValue>
        </application>
        <application>
            <appId>4</appId>
            <applicationName>ACS</applicationName>
            <organizationName>Whydah.net</organizationName>
            <roleName>Employee</roleName>
            <roleValue>Leon.Ho@altran.com</roleValue>
        </application>
    </applications>
</whydahuser>
